CREATE SCHEMA IF NOT EXISTS PROFILING_DATABASE;


--STUDENTS Table
CREATE TABLE IF NOT EXISTS profiling_database.students (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

--TEACHER TAble
CREATE TABLE IF NOT EXISTS profiling_database.teachers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);